version: 2
updates:
  # Enable version updates for Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    assignees:
      - "dudiedri"
    labels:
      - "dependencies"
      - "maven"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    rebase-strategy: "auto"
    groups:
      jackson:
        patterns:
          - "com.fasterxml.jackson*"
      test-dependencies:
        patterns:
          - "org.junit*"
          - "org.mockito*"
        dependency-type: "development"
      retrofit:
        patterns:
          - "com.squareup.retrofit2*"
          - "com.squareup.okhttp3*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "dudiedri"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"