name: Codecov

on: [push]

env:
  MAESTRO_API_KEY: ${{ secrets.MAESTRO_PREPROD_API_KEY }}
  MAESTRO_JAVA_LIB_LOGGING: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Ensure ~/.m2/repository exists
        run: mkdir -p ~/.m2/repository

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Set up Maven settings
        run: |
          mkdir -p $HOME/.m2
          cat <<EOF > $HOME/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GH_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Install Dependencies
        run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dgpg.skip

      - name: Run tests and collect coverage
        run: mvn '-Dtest=*Preprod*' -B test -Dgpg.skip

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
          verbose: true
