name: Mainnet

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

env:
  MAESTRO_API_KEY: ${{ secrets.MAESTRO_API_KEY }}
  MAESTRO_JAVA_LIB_LOGGING: true

jobs:
  mainnet:
    name: Mainnet Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run Integration Tests
        run: |
          mvn test -Dtest="*Mainnet*" -Djacoco.destFile=exportJacoco/jacoco-mainnet.exec
      - name: Upload Jacoco Results
        uses: actions/upload-artifact@v4
        with:
          name: mainnet-tests-jacoco
          path: exportJacoco/jacoco-mainnet.exec
        if: always()  # Upload even if tests fail
